<?php 
require_once("configu.php");
require_once("functions.php");
require_once("session.php");
require_once("database.php");
require_once("users.php");
require_once("photograph.php");
require_once("comments.php");
require_once("pagination.php");
require_once("phpmailer/class.phpmailer.php");
require_once("phpmailer/class.smtp.php");
?>